import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AuthProvider from "@/component/AuthProvider";

import Navbar from "@/component/Navbar";
import { Toaster } from "react-hot-toast";
import LoaderProvider from "@/component/loaderProvider";
import Footer from "@/component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=
        {`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <AuthProvider>
      <LoaderProvider>
           <Navbar/>
          {children}
          <Footer/>
        <Toaster></Toaster>
      </LoaderProvider>
      

       </AuthProvider>
     
    
  
      </body>
    </html>
  );
}
